import { StyleMetrics } from "std-widgets.slint";
import { SideBar } from "widgets/side_bar.slint";
import { CounterPage, CounterSingleton } from "pages/counter_page.slint";
import { FtpPage, FtpSingleton } from "pages/ftp_page.slint";
import { HttpPage, HttpSingleton } from "pages/http_page.slint";
import { MqttPage, MqttSingleton } from "pages/mqtt_page.slint";

export { CounterSingleton, FtpSingleton, HttpSingleton, MqttSingleton }

export global AppSingleton {
    in property<bool> curl-available: true;
    in property<bool> mosquitto-available: true;
    in property<[string]> menu-items: [];
    out property<string> counter-menu-item: @tr("Menu" => "Counter");
    out property<string> http-menu-item: @tr("Menu" => "HTTP");
    out property<string> ftp-menu-item: @tr("Menu" => "FTP");
    out property<string> mqtt-menu-item: @tr("Menu" => "MQTT");
}

export component AppWindow inherits Window {

    preferred-width: 700px;
    preferred-height: 500px;
    title: @tr("mecaps demo");

    sideBar := SideBar {
        title: @tr("mecaps demo");
        width: 200px;
        x: 0;
        model: AppSingleton.menu-items;
    }

    counter-page := CounterPage {
        visible: (sideBar.current-item == 0);
        width: root.width - sideBar.width;
        x: sideBar.x+sideBar.width;
    }

    http-page := HttpPage {
        visible: AppSingleton.curl-available && (sideBar.current-item == 1);
        width: root.width - sideBar.width;
        x: sideBar.x+sideBar.width;
    }

    ftp-page := FtpPage {
        visible: AppSingleton.curl-available && (sideBar.current-item == 2);
        width: root.width - sideBar.width;
        x: sideBar.x+sideBar.width;
    }

    mqtt-page := MqttPage {
        visible: AppSingleton.curl-available ? (sideBar.current-item == 3) : (sideBar.current-item == 1);
        width: root.width - sideBar.width;
        x: sideBar.x+sideBar.width;
    }
}
