import { GridBox, ListView, ScrollView, VerticalBox } from "std-widgets.slint";

// import { GallerySettings } from "../gallery_settings.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";

    VerticalLayout {
        height: 40px;

        Text {
            font-size: 20px;
            text <=> root.title;
        }
        Text {
            font-size: 15px;
            text <=> root.description;
        }

        // Spacer
        Rectangle {}
    }

    @children
}
