import { GridBox, ListView, ScrollView, VerticalBox } from "std-widgets.slint";

// import { GallerySettings } from "../gallery_settings.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";

    HorizontalLayout {
        height: 24px;

        Text {
            // color: black;
            font-size: 20px;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}
    }

    @children
}
