import { Button, VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    out property<string> url: input.text;
    in property<string> fetchedContent;

    callback request-increase-value();
    callback query-url();

    VerticalBox {
        HorizontalBox {
            spacing: 10px;
            VerticalBox {
                forward-focus: input;
                Text {
                    text: "Query a https URL";
                }
                Rectangle {
                    background: grey;
                    input := TextInput {
                        text: "https://example.com";
                    }
                }
                ScrollView {
                    Rectangle {
                        background: black;
                        Text {
                            text: fetchedContent;
                            color: white;
                        }
                    }
                }
                Button {
                    text: "Query";
                    clicked => {
                        root.query-url();
                    }
                }
            }

            VerticalBox {
                Text {
                    text: "Counter: \{root.counter}";
                }
                Button {
                    text: "Increase value";
                    clicked => {
                        root.request-increase-value();
                    }
                }
            }
        }
    }
}
